config/routes.rb
Rails.application.routes.draw do

  resources :events do 
    resources :comments
    match "/comments" => "comments#index", via: :options 
  end

  resources :posts do
    resources :comments
    match "/comments" => "comments#index", via: :options 
  end

  match "/posts" => "posts#index", via: :options  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/birthday.rb
class Birthday < Event
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :comments, as: :commentable, dependent: :destroy
	accepts_nested_attributes_for :comments
	TYPES = ['Birthday', 'Marriage', 'Upanayanam', 'MarriageAnniversary']
end

app/models/marriage.rb
class Marriage < Event
end

app/models/marriage_anniversary.rb
class MarriageAnniversary < Event
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, as: :commentable, dependent: :destroy
	accepts_nested_attributes_for :comments
end

app/models/upanayanam.rb
class Upanayanam < Event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	#protect_from_forgery with: :exception
	protect_from_forgery
	#respond_to(:html, :json)
	respond_to :html, :xml, :json
	before_filter :set_headers
	after_filter  :set_csrf_cookie_for_ng

	def set_headers
	  puts 'PostsController.set_headers'
	  if request.headers["HTTP_ORIGIN"]     
	  # better way check origin
	  # if request.headers["HTTP_ORIGIN"] && /^https?:\/\/(.*)\.some\.site\.com$/i.match(request.headers["HTTP_ORIGIN"])
	    headers['Access-Control-Allow-Origin'] = request.headers["HTTP_ORIGIN"]
	    headers['Access-Control-Expose-Headers'] = 'ETag'
	    headers['Access-Control-Allow-Methods'] = 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD'
	    headers['Access-Control-Allow-Headers'] = '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match,Auth-User-Token'
	    headers['Access-Control-Max-Age'] = '86400'
	    headers['Access-Control-Allow-Credentials'] = 'true'
	  end
	end

	def set_csrf_cookie_for_ng
	cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
	end

	protected

	def verified_request?
	super || form_authenticity_token == request.headers['X_XSRF_TOKEN']
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	#respond_to :html, :xml, :json

	# before_filter :set_headers

	# def set_headers
	#   puts 'CommentsController.set_headers'
	#   if request.headers["HTTP_ORIGIN"]     
	#   # better way check origin
	#   # if request.headers["HTTP_ORIGIN"] && /^https?:\/\/(.*)\.some\.site\.com$/i.match(request.headers["HTTP_ORIGIN"])
	#     headers['Access-Control-Allow-Origin'] = request.headers["HTTP_ORIGIN"]
	#     headers['Access-Control-Expose-Headers'] = 'ETag'
	#     headers['Access-Control-Allow-Methods'] = 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD'
	#     headers['Access-Control-Allow-Headers'] = '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match,Auth-User-Token'
	#     headers['Access-Control-Max-Age'] = '86400'
	#     headers['Access-Control-Allow-Credentials'] = 'true'
	#   end
	# end 

	def index
		@commentable = find_commentable
		@comments = @commentable.comments
		respond_to do |format|
		    format.html 
		    format.json { render json: @comments }
		end
	end

  def new
    @commentable = find_commentable
    @comment = @commentable.comments.new
  end

  def create
    @commentable = find_commentable
    @comment = @commentable.comments.new(comment_params)
    puts @commentable.inspect
    puts @comment.inspect

    if @comment.save
      redirect_to context_url(find_commentable), notice: "The comment has been successfully created."
    end
  end

  def edit
    @commentable = find_commentable
    @comment = @commentable.comments.find(params[:id])
  end

  def update
    @commentable = find_commentable
    @comment = @find_commentable.comments.find(params[:id])
    if @comment.update_attributes(comment_params)
      redirect_to context_url(find_commentable), notice: "The comment has been updated"
    end
  end

private
  def comment_params
    #params.require(:name, :created_by).permit!
    params.require(:comment).permit(:name, :created_by)
  end

  def context_url(context)
    if Event === context
      event_path(context)
    else
      post_path(context)
    end
  end

  def find_commentable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base

  private

    def event_params
      params.require(:event).permit(:name, :description, :event_on, :is_repeated, :type)
    end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base

	# before_filter :set_headers

	# # def index
	# #   puts "Do nothing."
	# #   render nothing: true
	# # end

	# def set_headers
	#   puts 'PostsController.set_headers'
	#   if request.headers["HTTP_ORIGIN"]     
	#   # better way check origin
	#   # if request.headers["HTTP_ORIGIN"] && /^https?:\/\/(.*)\.some\.site\.com$/i.match(request.headers["HTTP_ORIGIN"])
	#     headers['Access-Control-Allow-Origin'] = request.headers["HTTP_ORIGIN"]
	#     headers['Access-Control-Expose-Headers'] = 'ETag'
	#     headers['Access-Control-Allow-Methods'] = 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD'
	#     headers['Access-Control-Allow-Headers'] = '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match,Auth-User-Token'
	#     headers['Access-Control-Max-Age'] = '86400'
	#     headers['Access-Control-Allow-Credentials'] = 'true'
	#   end
	# end 

	def create
	  puts 'PostsController.create!!!!!'
	  post_param = params[:post]
	  puts post_param.inspect
	  @post = Post.create(post_params)
	  @post.save!
	  redirect_to @post
	end

  private

    def post_params
      params.require(:post).permit(:name, :body, :created_by)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper

	def days_left(event_object)
		daysRemain = (event_object.event_on - Time.now()).to_i
		oneDay = 86400000
		newDaysRemain = daysRemain*1000
		daysLeftOrComplete = newDaysRemain/86400000
		if daysLeftOrComplete
			case 
			when daysLeftOrComplete > 1
				(daysLeftOrComplete).ceil.to_s + ' Days Left'
			when daysLeftOrComplete == 1
				(daysLeftOrComplete).ceil.to_s + ' Days Left'
			when daysLeftOrComplete == 0
				newDaysRemain = daysRemain*1000 + 19800
				finalDaysRemain = newDaysRemain/(60*60*1000)
				(finalDaysRemain).ceil.to_s + ' Hours left.'
			when daysLeftOrComplete == -1
				newDaysRemain = (daysRemain*1000* -1) + 19800
				finalDaysRemain = newDaysRemain/(60*60*1000)
				(finalDaysRemain).ceil.to_s + ' Hours ago.'
			else
				daysLeftOrComplete = daysLeftOrComplete * - 1
				(daysLeftOrComplete).ceil.to_s + ' Days Completed'
			end
		end

	end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<h1>Editing Interaction for <%= @commentable.name %></h1>
<%= render "form" %>

app/views/comments/index.html.erb
<h3>All Comments</h3>
<!-- <p><%= @comments.inspect %></p> -->
<!-- Comment id: 3, name: "testing comment3", created_by: "Maheswari K", commentable_id: 4, commentable_type: "Post", created_at: "2016-02-21 17:32:48", updated_at: "2016-02-21 17:32:48" -->

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Created By</th>
      <th>Id</th>
      <th>Type</th>
      <th>Created On</th>
    </tr>
  </thead>
  <% if @comments.count > 0 %>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.created_by %></td>
        <td><%= comment.commentable_id %></td>
        <td><%= comment.commentable_type %></td>
        <td><%= time_ago_in_words comment.created_at %> ago</td>
        
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="2">No comments found for this posts.  Click the 'New comments' button to create a new comment.</td>
    </tr>
  <% end %>
</table>

app/views/comments/new.html.erb
<h1>New Comment for <%= @commentable.name %></h1>
<%= render "form" %>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :event_on %><br>
    <%= f.datetime_select :event_on %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.select :type, Event::TYPES %>
  </div>
  <div class="field">
    <%= f.label :is_repeated %><br>
    <%= f.check_box :is_repeated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Event on</th>
      <th>Event Type</th>
      <th>Days to Go</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.event_on %></td>
        <td><%= event.type %></td>
        <td><%= days_left(event) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Event on:</strong>
  <%= @event.event_on %>
</p>

<p>
  <strong>Event Type:</strong>
  <%= @event.type %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

<div class="col-md-12">
  <%= link_to "New Comments", new_event_comment_path(@event), class: "btn btn-primary" %>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Created By</th>
      <th>Created On</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <% if @event.comments.count > 0 %>
    <% @event.comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.created_by %></td>
        <td><%= time_ago_in_words comment.created_at %> ago</td>
        <td><%= link_to "Edit", edit_event_comment_path(@event, comment), class:"btn btn-default" %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="2">No comments found for this events.  Click the 'New comments' button to create a new comment.</td>
    </tr>
  <% end %>
</table>

app/views/layouts/_navbar.html.erb
<%= nav_bar fixed: :top, brand: "Cherukuwada Application", responsive: true do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_divider %>
        <%= menu_item "Posts", posts_path %>
        <%= menu_item "Events", events_path %>
    <% end %>
    <%= menu_group pull: :right do %>
        <%= menu_item "Log Out", posts_path %>        
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CherukuwadaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navbar' %>
	<div class="ca-body-container container">			
		<%= yield %>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.text_field :created_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h3>Editing Post</h3>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Posts</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Created By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.body %></td>
        <td><%= post.created_by %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h3>New Post</h3>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @post.created_by %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<div class="col-md-12">
  <%= link_to "New Comments", new_post_comment_path(@post), class: "btn btn-primary" %>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Created By</th>
      <th>Created On</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <% if @post.comments.count > 0 %>
    <% @post.comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.created_by %></td>
        <td><%= time_ago_in_words comment.created_at %> ago</td>
        <td><%= link_to "Edit", edit_post_comment_path(@post, comment), class:"btn btn-default" %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="2">No comments found for this posts.  Click the 'New comments' button to create a new comment.</td>
    </tr>
  <% end %>
</table>

app/views/welcome/index.html.erb
<h1 class="ca-title text-center">Welcome to Cherukuwada Application</h1>
<p>This is welcome page for Cherukuwada Application</p>